apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  POSTGRES_DB: todo_app
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_HOST: localhost
  POSTGRES_PORT: "5432"
